blank_issues_enabled: false
contact_links:
  - name: WebContainer related issues
    url: https://github.com/stackblitz/webcontainer-core/issues/new/choose
    about: Report issues related to WebContainer (not webdev.ai)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other webdev.ai users.
